PROJECT = device_manager
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.2

DEPS = exec srly ebus erlydtl
LOCAL_DEPS = sasl

dep_ebus = git https://github.com/cabol/erlbus

include ../../erlang.mk
